import type { Metadata } from "next";
import { Box } from "@mui/material";


export const metadata: Metadata = {
    title: "Admin challenge",
    description: "Generated by challenge",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Box>
            {children}
        </Box>
    );
}
